### ISSUE TITLE
Allow manual bulk drink entry

### ISSUE THREAD

**Issue by robzienert** [CellarHQ/cellarhq.com#258]
From a discussion with @boggebe:

Add the ability to rapidly enter new beers from the Your Cellar page. You could enter a "rapid mode" or something to that effect which would scroll the browser down to the bottom of the beer list table, adding a new inline form within the table, where each column is editable. The cog would be changed to have a save & cancel action, but tabbing on the last field would also save and add a new row. Upon adding a new row, the previous form would be submitted and the form would be cleared, ready for additional entries.

A user who wants to add additional information to the rapidly added drinks would need to go back and fill the information.

**Comment by mostlylikeable** [comment]
🚀
